//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workvivo.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClutureResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClutureResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workvivo.Resources.Resources.ClutureResource", typeof(ClutureResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Required.
        /// </summary>
        public static string AttachmentsRequired {
            get {
                return ResourceManager.GetString("AttachmentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Saved Successfully.
        /// </summary>
        public static string AutoSavedSuccessfully {
            get {
                return ResourceManager.GetString("AutoSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosable.
        /// </summary>
        public static string Choosable {
            get {
                return ResourceManager.GetString("Choosable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Invalid.
        /// </summary>
        public static string DataInvalid {
            get {
                return ResourceManager.GetString("DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered or the ID is already registered.
        /// </summary>
        public static string EmailAndIdAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAndIdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of variables within an email template must be {0} variables.
        /// </summary>
        public static string EmailVariableRequired {
            get {
                return ResourceManager.GetString("EmailVariableRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred While Sending.
        /// </summary>
        public static string ErrorOccurredWhileSending {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild Save.
        /// </summary>
        public static string FaildSave {
            get {
                return ResourceManager.GetString("FaildSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many failed login attempts. Please try again after {0} minutes..
        /// </summary>
        public static string FailedLoginPleaseTryAgainAfterMinutes {
            get {
                return ResourceManager.GetString("FailedLoginPleaseTryAgainAfterMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Retrieve Data.
        /// </summary>
        public static string FailedRetrieveData {
            get {
                return ResourceManager.GetString("FailedRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This accountis temporarily suspended. Please check with your system administrator.
        /// </summary>
        public static string InActiveAccount {
            get {
                return ResourceManager.GetString("InActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item cannot be deleted because it is used in the system.
        /// </summary>
        public static string ItemCannotBeDeleted {
            get {
                return ResourceManager.GetString("ItemCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National identity is invalid.
        /// </summary>
        public static string NationalIdentityInvalid {
            get {
                return ResourceManager.GetString("NationalIdentityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chat found.
        /// </summary>
        public static string NoChatFound {
            get {
                return ResourceManager.GetString("NoChatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotApplied {
            get {
                return ResourceManager.GetString("NotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order of the variables within the email template should be as follows ({0}).
        /// </summary>
        public static string OrderOfVariablesRequired {
            get {
                return ResourceManager.GetString("OrderOfVariablesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step cannot be processed until the previous step has been approved.
        /// </summary>
        public static string PreviousStepHasNotBeenApproved {
            get {
                return ResourceManager.GetString("PreviousStepHasNotBeenApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to enter all data related to the financing structure.
        /// </summary>
        public static string RequiredFinancingStructure {
            get {
                return ResourceManager.GetString("RequiredFinancingStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Data.
        /// </summary>
        public static string RetrieveData {
            get {
                return ResourceManager.GetString("RetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sened successfully.
        /// </summary>
        public static string SenedSuccessfully {
            get {
                return ResourceManager.GetString("SenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Approved.
        /// </summary>
        public static string SuccessfullyApproved {
            get {
                return ResourceManager.GetString("SuccessfullyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Rejected.
        /// </summary>
        public static string SuccessfullyRejected {
            get {
                return ResourceManager.GetString("SuccessfullyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Action.
        /// </summary>
        public static string TakeAction {
            get {
                return ResourceManager.GetString("TakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group cannot be deleted for use in the system.
        /// </summary>
        public static string TheGroupCannotBeDeletedForUseInTheSystem {
            get {
                return ResourceManager.GetString("TheGroupCannotBeDeletedForUseInTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control has no instructions.
        /// </summary>
        public static string ThisControlHasnoInstructions {
            get {
                return ResourceManager.GetString("ThisControlHasnoInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has already been rejected. No action can be taken at this time.
        /// </summary>
        public static string UserRejectedCannotTakeAction {
            get {
                return ResourceManager.GetString("UserRejectedCannotTakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission as an administration user to access the portal.
        /// </summary>
        public static string YouDoNotHavePermissionAsAdministrationUserToAccessPortal {
            get {
                return ResourceManager.GetString("YouDoNotHavePermissionAsAdministrationUserToAccessPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission as a Managment user to enter the administration.
        /// </summary>
        public static string YouDoNotHavePermissionAsManagmentUserToEnterAdministration {
            get {
                return ResourceManager.GetString("YouDoNotHavePermissionAsManagmentUserToEnterAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Do Not Have Permission To Open This Screen . Please check with your system administrator.
        /// </summary>
        public static string YouDoNotHavePermissionForScreen {
            get {
                return ResourceManager.GetString("YouDoNotHavePermissionForScreen", resourceCulture);
            }
        }
    }
}
