// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workvivo.Infrastructure.DBContext;

#nullable disable

namespace Workvivo.Infrastructure.Migrations
{
    [DbContext(typeof(Workvivo_DbContext))]
    [Migration("20260909182656_PinSeededRoleConcurrencyStamp")]
    partial class PinSeededRoleConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.AccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Access_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Action_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Domain_Controller_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Main_Module_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action_Code");

                    b.HasIndex("Main_Module_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Security_AccessLogs");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.EmailSMSHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachment_Files")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BCCEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email_Sender_Display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Error_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Sent")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Last_Modified_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Last_Modify_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Last_Resend_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Priority")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Record_Insertion_Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Resend_Try")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Template_Id")
                        .HasColumnType("int");

                    b.Property<string>("To_Emails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Template_Id");

                    b.ToTable("EmailSMSHistory");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.EmailSMSTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HTML_Template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTML_Template_Defult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTML_Template_Variables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("SMS_Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Screen_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Screen_Id");

                    b.ToTable("EmailSMSTemplates");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.GlobalAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Document_Id")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileMIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("GlobalAttachments");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.LinkScreenAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Base_Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Screen_Action_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Screen_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Screen_Action_Id");

                    b.HasIndex("Screen_Id");

                    b.ToTable("Common_LinkScreenActions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f68dc32-021a-43fd-8ee1-023c1ce402a4"),
                            Action_Code = "AAEGA",
                            Base_Route = "managment/api/Group/CreateGroup",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("f820b435-d621-41a8-80e4-32d5d1f867c7"),
                            Screen_Id = new Guid("e3035fc1-9b23-49b5-90f7-470f79ad1d5b")
                        },
                        new
                        {
                            Id = new Guid("48984f43-658b-4adf-8788-248f54d1faa0"),
                            Action_Code = "GUACS",
                            Base_Route = "managment/api/GroupAction/Get",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("6ebd6ae4-7f43-45b6-9d57-aa5067a4b79f"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd6d-5f8320c3a24d")
                        },
                        new
                        {
                            Id = new Guid("e4ffa587-2100-4f64-8794-29c9162d4ce8"),
                            Action_Code = "DDDGA",
                            Base_Route = "managment/api/Group/DeleteGroup",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("328723da-e3c9-468e-998d-6adea7217d37"),
                            Screen_Id = new Guid("e3035fc1-9b23-49b5-90f7-470f79ad1d5b")
                        },
                        new
                        {
                            Id = new Guid("e80a271d-97e9-4896-8442-4193e3d8f8c3"),
                            Action_Code = "GCSRS",
                            Base_Route = "managment/api/User/GetUser",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("6ebd6ae4-7f43-45b6-9d57-aa5067a4b79f"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd9d-5f8310c3a24d")
                        },
                        new
                        {
                            Id = new Guid("7e7e47f6-961b-4c60-9b3a-62981dc83326"),
                            Action_Code = "AAEUA",
                            Base_Route = "managment/api/GroupAction/AddEdit",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("4add3d50-f32c-4abe-b8e2-3af596588a71"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd6d-5f8320c3a24d")
                        },
                        new
                        {
                            Id = new Guid("9741c3a7-167b-4731-92dd-6ec28780f520"),
                            Action_Code = "EUSRA",
                            Base_Route = "managment/api/User/EditUser",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("4add3d50-f32c-4abe-b8e2-3af596588a71"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd9d-5f8310c3a24d")
                        },
                        new
                        {
                            Id = new Guid("b6a4e50e-9ec8-45fb-ae22-807f10b2679e"),
                            Action_Code = "DUSRA",
                            Base_Route = "managment/api/User/DeleteUser",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("328723da-e3c9-468e-998d-6adea7217d37"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd9d-5f8310c3a24d")
                        },
                        new
                        {
                            Id = new Guid("ff0f7c6d-b778-41dc-9524-9d2961326ee6"),
                            Action_Code = "CUSRA",
                            Base_Route = "managment/api/User/CreateUser",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("f820b435-d621-41a8-80e4-32d5d1f867c7"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd9d-5f8310c3a24d")
                        },
                        new
                        {
                            Id = new Guid("8fde4946-152d-45d5-96a0-e25d5f2cb274"),
                            Action_Code = "DDDUA",
                            Base_Route = "managment/api/GroupAction/Delete",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("328723da-e3c9-468e-998d-6adea7217d37"),
                            Screen_Id = new Guid("e70a846e-7a3c-4ab4-bd6d-5f8320c3a24d")
                        },
                        new
                        {
                            Id = new Guid("77c404d1-2f37-4728-9608-e9b19194ae07"),
                            Action_Code = "EAEGA",
                            Base_Route = "managment/api/Group/EditGroup",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("4add3d50-f32c-4abe-b8e2-3af596588a71"),
                            Screen_Id = new Guid("e3035fc1-9b23-49b5-90f7-470f79ad1d5b")
                        },
                        new
                        {
                            Id = new Guid("0c2244d0-fc92-479f-9d57-ffe9a38a0246"),
                            Action_Code = "GGGGA",
                            Base_Route = "managment/api/Group/GetGroups",
                            Is_Deleted = false,
                            Screen_Action_Id = new Guid("6ebd6ae4-7f43-45b6-9d57-aa5067a4b79f"),
                            Screen_Id = new Guid("e3035fc1-9b23-49b5-90f7-470f79ad1d5b")
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Category_Code");

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.LookupCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Changable_By_User")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.MainModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApplicationNo")
                        .HasColumnType("int");

                    b.Property<string>("Description_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Common_MainModules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a0b5a10-9b94-4888-a835-d2b7a9360d1e"),
                            ApplicationNo = 2,
                            Description_Ar = "البوابة",
                            Description_En = "Portal",
                            Is_Deleted = false
                        },
                        new
                        {
                            Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            ApplicationNo = 1,
                            Description_Ar = "الإدارة",
                            Description_En = "Managment",
                            Is_Deleted = false
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.MasterData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Item_Order")
                        .HasColumnType("int");

                    b.Property<string>("Master_Data_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Master_Data_Parent_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Master_Data_Parent_Id");

                    b.ToTable("Security_MasterData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category_Name = "UserType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "USTYP",
                            Title_Ar = "نوع المستخدم",
                            Title_En = "User Type"
                        },
                        new
                        {
                            Id = 2,
                            Category_Name = "UserType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "MANAG",
                            Master_Data_Parent_Id = 1,
                            Title_Ar = "مدير إدارة",
                            Title_En = "Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Category_Name = "UserType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 2,
                            Master_Data_Code = "PORTA",
                            Master_Data_Parent_Id = 1,
                            Title_Ar = "مستخدم بوابة",
                            Title_En = "User Portal"
                        },
                        new
                        {
                            Id = 4,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "REQST",
                            Title_Ar = "حالة الطلب",
                            Title_En = "Request Status"
                        },
                        new
                        {
                            Id = 5,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "DRAFT",
                            Master_Data_Parent_Id = 4,
                            Title_Ar = "نسخة",
                            Title_En = "Draft"
                        },
                        new
                        {
                            Id = 6,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 2,
                            Master_Data_Code = "APPRO",
                            Master_Data_Parent_Id = 4,
                            Title_Ar = "معتمد",
                            Title_En = "Approved"
                        },
                        new
                        {
                            Id = 7,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 3,
                            Master_Data_Code = "REJEC",
                            Master_Data_Parent_Id = 4,
                            Title_Ar = "مرفوض",
                            Title_En = "Rejected"
                        },
                        new
                        {
                            Id = 8,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 5,
                            Master_Data_Code = "UNPRC",
                            Master_Data_Parent_Id = 4,
                            Title_Ar = "مرسل",
                            Title_En = "Sent"
                        },
                        new
                        {
                            Id = 9,
                            Category_Name = "RquestStatus",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 6,
                            Master_Data_Code = "STOPD",
                            Master_Data_Parent_Id = 4,
                            Title_Ar = "موقوف",
                            Title_En = "Stopped"
                        },
                        new
                        {
                            Id = 10,
                            Category_Name = "IssuerType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "ISSTY",
                            Title_Ar = "نوع المصدر",
                            Title_En = "Issuer Type"
                        },
                        new
                        {
                            Id = 11,
                            Category_Name = "IssuerType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 1,
                            Master_Data_Code = "DIREC",
                            Master_Data_Parent_Id = 10,
                            Title_Ar = "إدخال مباشر",
                            Title_En = "Direct entry"
                        },
                        new
                        {
                            Id = 12,
                            Category_Name = "IssuerType",
                            Is_Active = true,
                            Is_Deleted = false,
                            Item_Order = 2,
                            Master_Data_Code = "IMPOR",
                            Master_Data_Parent_Id = 10,
                            Title_Ar = "استيراد بيانات",
                            Title_En = "Import data"
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Branch")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Main_Module_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Menu_Or_Not")
                        .HasColumnType("bit");

                    b.Property<bool>("No_Login")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("Parent_Screen_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Screen_Description_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screen_Description_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screen_Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Main_Module_Id");

                    b.HasIndex("Parent_Screen_Id");

                    b.ToTable("Common_Screens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("503adb95-49a7-4fe7-b28c-0be7456c91be"),
                            Is_Branch = false,
                            Is_Deleted = false,
                            Link = "admin/home",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 1,
                            Screen_Description_Ar = "لوحة القيادة",
                            Screen_Description_En = "Dashboard",
                            Screen_Icon = "mat_outline:home_work"
                        },
                        new
                        {
                            Id = new Guid("e3035fc1-9b23-49b5-90f7-470f79ad1d5b"),
                            Is_Branch = true,
                            Is_Deleted = false,
                            Link = "admin/groupDefinition",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 1,
                            Parent_Screen_Id = new Guid("619bcf7f-bd18-4b93-a8ca-a0f400ed105b"),
                            Screen_Description_Ar = "تعريف المجموعات",
                            Screen_Description_En = "Group Definition",
                            Screen_Icon = "heroicons_outline:user-group"
                        },
                        new
                        {
                            Id = new Guid("e70a846e-7a3c-4ab4-bd9d-5f8310c3a24d"),
                            Is_Branch = true,
                            Is_Deleted = false,
                            Link = "admin/contacts",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 1,
                            Parent_Screen_Id = new Guid("619bcf7f-bd18-4b93-a8ca-a0f400ed105b"),
                            Screen_Description_Ar = "المستخدمين",
                            Screen_Description_En = "Users",
                            Screen_Icon = "heroicons_outline:users"
                        },
                        new
                        {
                            Id = new Guid("e70a846e-7a3c-4ab4-bd6d-5f8320c3a24d"),
                            Is_Branch = true,
                            Is_Deleted = false,
                            Link = "admin/permission",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 1,
                            Parent_Screen_Id = new Guid("619bcf7f-bd18-4b93-a8ca-a0f400ed105b"),
                            Screen_Description_Ar = "صلاحيات المستخدمين",
                            Screen_Description_En = "User Permission",
                            Screen_Icon = "heroicons_outline:key"
                        },
                        new
                        {
                            Id = new Guid("fea9385d-7c1d-43ed-ae82-6c2fa1e48690"),
                            Is_Branch = false,
                            Is_Deleted = false,
                            Link = "#",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 4,
                            Screen_Description_Ar = "التقارير",
                            Screen_Description_En = "Reports",
                            Screen_Icon = "heroicons_outline:clipboard-document-list"
                        },
                        new
                        {
                            Id = new Guid("619bcf7f-bd18-4b93-a8ca-a0f400ed105b"),
                            Is_Branch = false,
                            Is_Deleted = false,
                            Link = "#",
                            Main_Module_Id = new Guid("986b68ac-22ff-4cee-991d-dbdfe4b12bbb"),
                            Menu_Or_Not = true,
                            No_Login = true,
                            Order = 2,
                            Screen_Description_Ar = "الحماية",
                            Screen_Description_En = "SECURITY",
                            Screen_Icon = "heroicons_outline:shield-exclamation"
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.ScreenAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action_Name_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action_Name_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Common_ScreenActions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1577510-4bb5-49c1-a5e4-05b001c41e7e"),
                            Action_Name_Ar = "حفظ",
                            Action_Name_En = "Save",
                            Is_Deleted = false,
                            Order = 13
                        },
                        new
                        {
                            Id = new Guid("2f5a8589-6e31-4514-885c-072cfb38f000"),
                            Action_Name_Ar = "تفعيل",
                            Action_Name_En = "Activation",
                            Is_Deleted = false,
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("f820b435-d621-41a8-80e4-32d5d1f867c7"),
                            Action_Name_Ar = "إضافة",
                            Action_Name_En = "Add",
                            Is_Deleted = false,
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("609b4ce8-1c5f-4ff7-a71e-3462436f3f11"),
                            Action_Name_Ar = "إسترجاع",
                            Action_Name_En = "Retrieve",
                            Is_Deleted = false,
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("4add3d50-f32c-4abe-b8e2-3af596588a71"),
                            Action_Name_Ar = "تعديل",
                            Action_Name_En = "Edit",
                            Is_Deleted = false,
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("8a231277-b772-4c59-844e-54435dc912f1"),
                            Action_Name_Ar = "إعتماد",
                            Action_Name_En = "Approve",
                            Is_Deleted = false,
                            Order = 11
                        },
                        new
                        {
                            Id = new Guid("328723da-e3c9-468e-998d-6adea7217d37"),
                            Action_Name_Ar = "حذف",
                            Action_Name_En = "Delete",
                            Is_Deleted = false,
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("2dfa1eaf-97c4-4b85-b548-6d38334735e9"),
                            Action_Name_Ar = "إرسال بريد إلكتروني",
                            Action_Name_En = "Send Email",
                            Is_Deleted = false,
                            Order = 10
                        },
                        new
                        {
                            Id = new Guid("6ebd6ae4-7f43-45b6-9d57-aa5067a4b79f"),
                            Action_Name_Ar = "فتح",
                            Action_Name_En = "View",
                            Is_Deleted = false,
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("67fbc65e-214d-46f5-9fa6-afe35cd9c3f3"),
                            Action_Name_Ar = "تقديم",
                            Action_Name_En = "Submit",
                            Is_Deleted = false,
                            Order = 8
                        },
                        new
                        {
                            Id = new Guid("211bd794-ffba-4305-a278-d25d206f18af"),
                            Action_Name_Ar = "إستيراد بيانات",
                            Action_Name_En = "Import Data",
                            Is_Deleted = false,
                            Order = 12
                        },
                        new
                        {
                            Id = new Guid("f3fc395d-72d8-4432-b273-ea1d3efb5403"),
                            Action_Name_Ar = "طباعة",
                            Action_Name_En = "Print",
                            Is_Deleted = false,
                            Order = 7
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.SysSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DataTypeMasterDataId")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("SysSettingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysSettingDescAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysSettingDescEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SysSettingID")
                        .HasColumnType("int");

                    b.Property<string>("SysSettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysSettingValueDataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeMasterDataId");

                    b.ToTable("SysSetting");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.UserLoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginLogs");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.UsersShortCuts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IconMasterDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRouter")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IconMasterDataId");

                    b.HasIndex("UserID");

                    b.ToTable("Users_ShortCuts");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DepartmentNo")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Full_Name_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name_En")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Manager")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Last_Modified_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Last_Modify_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagNo")
                        .HasColumnType("int");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Office_TelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile_PictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signee_PictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("User_Type")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("User_Type");

                    b.ToTable("Security_Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f6c1f5a-3c9e-4c2b-9d17-2a5b4e7c1d90"),
                            ConcurrencyStamp = "c47b9e21-5d38-4f60-a913-7e2b8c4d6f05",
                            Create_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "must345@yahoo.com",
                            EmailConfirmed = true,
                            Full_Name_Ar = "مصطفى محمود",
                            Full_Name_En = "Mostafa Mahmoud",
                            Is_Active = true,
                            Is_Admin = true,
                            Is_Deleted = false,
                            Is_Manager = false,
                            ManagNo = 1,
                            MobileNo = "0564899515",
                            NormalizedEmail = "MUST345@YAHOO.COM",
                            NormalizedUserName = "DEV",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOc/l+BJqo9HCOS4X6JZSMccZGEliVV0wW8Raa9FutxSoJ+HkJ3D4m/cgElTwiPBw==",
                            SecurityStamp = "6a1f0c3d-9b2e-4a57-8c31-0d5e7f9a2b46",
                            UserName = "dev",
                            User_Type = "MANAG"
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.GroupPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Group_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Link_Screen_Action_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Link_Screen_Action_Id");

                    b.ToTable("Security_GroupPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d096d0b6-6d8b-4d45-af7e-0263cb10915f"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("1f68dc32-021a-43fd-8ee1-023c1ce402a4")
                        },
                        new
                        {
                            Id = new Guid("08eb862e-814e-4de3-8827-34baba6c5868"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("48984f43-658b-4adf-8788-248f54d1faa0")
                        },
                        new
                        {
                            Id = new Guid("e001ef51-8af3-4bfa-87a7-361c89b8060b"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("e4ffa587-2100-4f64-8794-29c9162d4ce8")
                        },
                        new
                        {
                            Id = new Guid("b33feaef-5eb5-406f-8d75-3cd783eec7fb"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("e80a271d-97e9-4896-8442-4193e3d8f8c3")
                        },
                        new
                        {
                            Id = new Guid("444734f1-be36-4fab-b2c6-77e74386960e"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("7e7e47f6-961b-4c60-9b3a-62981dc83326")
                        },
                        new
                        {
                            Id = new Guid("32429140-179e-4df8-a2a0-7b7f187f3259"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("9741c3a7-167b-4731-92dd-6ec28780f520")
                        },
                        new
                        {
                            Id = new Guid("13addee3-f52c-46f9-9e1b-94c44bd31d60"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("b6a4e50e-9ec8-45fb-ae22-807f10b2679e")
                        },
                        new
                        {
                            Id = new Guid("b2b92c00-f4d0-4bea-9e48-e153e71f3649"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("ff0f7c6d-b778-41dc-9524-9d2961326ee6")
                        },
                        new
                        {
                            Id = new Guid("0a1f7123-3068-453e-ae72-ec8f3f673eea"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("8fde4946-152d-45d5-96a0-e25d5f2cb274")
                        },
                        new
                        {
                            Id = new Guid("852c6945-708d-4a3b-86a8-f13eb9bfc0ba"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("77c404d1-2f37-4728-9608-e9b19194ae07")
                        },
                        new
                        {
                            Id = new Guid("5f794278-2c3f-48d2-b7f0-f318dadd3331"),
                            Group_Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            Is_Deleted = false,
                            Link_Screen_Action_Id = new Guid("0c2244d0-fc92-479f-9d57-ffe9a38a0246")
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Last_Modify_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Last_Modify_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("User_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("User_Type");

                    b.ToTable("Security_UserGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b"),
                            ConcurrencyStamp = "3e9a71d4-0b62-4c8f-95a1-7d4e2f6b8c30",
                            Create_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created_By = new Guid("8f6c1f5a-3c9e-4c2b-9d17-2a5b4e7c1d90"),
                            Is_Active = true,
                            Is_Deleted = false,
                            Name = "HKJHW",
                            Name_Ar = "مدير إدارة",
                            Name_En = "Administrator",
                            NormalizedName = "HKJHW",
                            User_Type = "MANAG"
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserGroupsLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_Id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Group_Id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Security_UserGroupsLink", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8f6c1f5a-3c9e-4c2b-9d17-2a5b4e7c1d90"),
                            RoleId = new Guid("b2d4e6f8-1a3c-4e5f-8b7a-9c0d1e2f3a4b")
                        });
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Link_Screen_Action_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Link_Screen_Action_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Security_UserPermissions");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.RealTime.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Header_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Last_Modified_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Last_Modify_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notification_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Notification_Type")
                        .HasColumnType("int");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.RealTime.NotificationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IS_Seen")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Notification_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Reciever_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Notification_Id");

                    b.HasIndex("Reciever_Id");

                    b.ToTable("NotificationUsers");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Views.VW_UserActions", b =>
                {
                    b.Property<string>("Action_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action_Name_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action_Name_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base_Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Screen_Action_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Screen_Description_Ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screen_Description_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("VW_UserActions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.AccessLog", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.LinkScreenAction", "LinkScreenAction")
                        .WithMany("AccessLogs")
                        .HasForeignKey("Action_Code")
                        .HasPrincipalKey("Action_Code");

                    b.HasOne("Workvivo.Domain.Entities.Common.MainModule", "MainModule")
                        .WithMany("AccessLogs")
                        .HasForeignKey("Main_Module_Id");

                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("AccessLogs")
                        .HasForeignKey("User_Id");

                    b.Navigation("ApplicationUser");

                    b.Navigation("LinkScreenAction");

                    b.Navigation("MainModule");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.EmailSMSHistory", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.EmailSMSTemplate", "EmailSMSTemplate")
                        .WithMany("EmailSMSHistories")
                        .HasForeignKey("Template_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailSMSTemplate");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.EmailSMSTemplate", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.Screen", "Screen")
                        .WithMany("EmailSMSTemplates")
                        .HasForeignKey("Screen_Id");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.GlobalAttachment", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Attachments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.LinkScreenAction", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.ScreenAction", "ScreenAction")
                        .WithMany("LinkScreenActions")
                        .HasForeignKey("Screen_Action_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Common.Screen", "Screen")
                        .WithMany("LinkScreenActions")
                        .HasForeignKey("Screen_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");

                    b.Navigation("ScreenAction");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.Lookup", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.LookupCategory", "LookupCategory")
                        .WithMany("Lookups")
                        .HasForeignKey("Category_Code")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupCategory");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.MasterData", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MasterData", "MasterDataParent")
                        .WithMany("MasterDataChilds")
                        .HasForeignKey("Master_Data_Parent_Id");

                    b.Navigation("MasterDataParent");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.Screen", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MainModule", "MainModule")
                        .WithMany("Screens")
                        .HasForeignKey("Main_Module_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Common.Screen", "ParentScreen")
                        .WithMany("SubScreens")
                        .HasForeignKey("Parent_Screen_Id");

                    b.Navigation("MainModule");

                    b.Navigation("ParentScreen");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.SysSetting", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MasterData", "DataTypeMasterData")
                        .WithMany("SysSettings")
                        .HasForeignKey("DataTypeMasterDataId");

                    b.Navigation("DataTypeMasterData");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.UserLoginLog", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserLoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.UsersShortCuts", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MasterData", "IconMasterData")
                        .WithMany("UsersShortCutsIcons")
                        .HasForeignKey("IconMasterDataId");

                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UsersShortCuts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IconMasterData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MasterData", "MastarDataUserType")
                        .WithMany("ApplicationUserUserType")
                        .HasForeignKey("User_Type")
                        .HasPrincipalKey("Master_Data_Code");

                    b.Navigation("MastarDataUserType");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.GroupPermissions", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.UserGroup", "Role")
                        .WithMany("RoleActions")
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Common.LinkScreenAction", "Action")
                        .WithMany("GroupActions")
                        .HasForeignKey("Link_Screen_Action_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserGroup", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.MasterData", "UserType")
                        .WithMany("UserGroups")
                        .HasForeignKey("User_Type")
                        .HasPrincipalKey("Master_Data_Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserGroupsLink", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.UserGroup", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserPermissions", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Common.LinkScreenAction", "Action")
                        .WithMany("UserActions")
                        .HasForeignKey("Link_Screen_Action_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserActions")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.RealTime.Notification", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "CreatorUser")
                        .WithMany("Notifications")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.RealTime.NotificationUser", b =>
                {
                    b.HasOne("Workvivo.Domain.Entities.RealTime.Notification", "Notification")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("Notification_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workvivo.Domain.Entities.Identity.ApplicationUser", "Reciever")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("Reciever_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Reciever");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.EmailSMSTemplate", b =>
                {
                    b.Navigation("EmailSMSHistories");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.LinkScreenAction", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("GroupActions");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.LookupCategory", b =>
                {
                    b.Navigation("Lookups");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.MainModule", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Screens");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.MasterData", b =>
                {
                    b.Navigation("ApplicationUserUserType");

                    b.Navigation("MasterDataChilds");

                    b.Navigation("SysSettings");

                    b.Navigation("UserGroups");

                    b.Navigation("UsersShortCutsIcons");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.Screen", b =>
                {
                    b.Navigation("EmailSMSTemplates");

                    b.Navigation("LinkScreenActions");

                    b.Navigation("SubScreens");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Common.ScreenAction", b =>
                {
                    b.Navigation("LinkScreenActions");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Attachments");

                    b.Navigation("NotificationUsers");

                    b.Navigation("Notifications");

                    b.Navigation("UserActions");

                    b.Navigation("UserLoginLogs");

                    b.Navigation("UserRoles");

                    b.Navigation("UsersShortCuts");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.Identity.UserGroup", b =>
                {
                    b.Navigation("RoleActions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Workvivo.Domain.Entities.RealTime.Notification", b =>
                {
                    b.Navigation("NotificationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
