<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Workvivo.Resources</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources\ClutureResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClutureResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ClutureResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ClutureResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
